# -*- coding: utf-8 -*-
"""DescargaGT_GH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBjYytUJLZcSI1YsLKPNLBs-u2eUmZ3y
"""

import pandas as pd
import matplotlib.pyplot as plt
from pytrends.request import TrendReq
import time

country_terms = {
    "CL": {"kw": "Bolsa de valores", "hl": "es-CL", "tz": -180},
}

timeframe = "2020-11-22 2025-11-09"

def get_trends(keyword, geo, hl, tz, timeframe=timeframe):
    pytrends = TrendReq(hl=hl, tz=tz)
    pytrends.build_payload([keyword], geo=geo, timeframe=timeframe)
    data = pytrends.interest_over_time().reset_index()

    if "isPartial" in data.columns:
        data = data.drop(columns=["isPartial"])

    data = data[["date", keyword]]
    data.columns = ["date", "value"]
    return data

for geo, info in country_terms.items():
    keyword = info["kw"]
    hl = info["hl"]
    tz = info["tz"]

    print(f"Descargando datos para {geo} — término: {keyword}")
    df = get_trends(keyword, geo, hl, tz)

    today = pd.Timestamp.today().date()
    df.to_excel(f"DatosGT_{geo}_{today}.xlsx", index=False)
    print(f"Archivo guardado como DatosGT_{geo}_{today}.xlsx")

    time.sleep(20)