# -*- coding: utf-8 -*-
"""DescargaGT_GitHub_MILA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108FSVjWFhJkjLnuiw6kFUyAlYnlfDDkV
"""

import pandas as pd
from pathlib import Path
from pytrends.request import TrendReq
from datetime import datetime
import time
import re

output_folder = Path("output")
output_folder.mkdir(parents=True, exist_ok=True)

today = datetime.today().strftime("%Y-%m-%d")

keywords_by_country = {
    "CL": ["Latam", "SQM", "IPSA", "Bolsa de valores"],
    "CO": ["Ecopetrol", "Bancolombia", "Colcap", "Bolsa de valores"],
    "PE": ["Credicorp", "Southern Copper Corporation", "Bolsa de valores de lima", "Bolsa de valores"],
    "MX": ["Grupo méxico", "América móvil", "Índice de precios y cotizaciones", "Bolsa de valores"]
}

bloques = [
    ("2017-04-27", "2022-04-27"),
    ("2021-04-27", "2026-04-27")
]

def clean_filename(text):
    text = text.lower().replace(" ", "_")
    replacements = {
        "á": "a", "é": "e", "í": "i",
        "ó": "o", "ú": "u", "ñ": "n"
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^a-zA-Z0-9_]", "", text)
    return text

pytrends = TrendReq(
    hl="es-ES",
    tz=300,
    timeout=(10, 25),
    retries=2,
    backoff_factor=0.5
)

for country, keywords in keywords_by_country.items():
    print(f"\n🌎 País: {country}")

    for keyword in keywords:
        keyword_clean = clean_filename(keyword)

        for bloque_i, (inicio, fin) in enumerate(bloques, start=1):
            timeframe = f"{inicio} {fin}"

            print(f"🔍 {country} | {keyword} | bloque {bloque_i}")

            try:
                pytrends.build_payload(
                    kw_list=[keyword],
                    cat=0,
                    timeframe=timeframe,
                    geo=country,
                    gprop=""
                )

                data = pytrends.interest_over_time()

                if data.empty:
                    print(f"⚠️ Sin datos: {country} - {keyword} - bloque {bloque_i}")
                    continue

                if "isPartial" in data.columns:
                    data = data.drop(columns=["isPartial"])

                data = data.reset_index()

                df = data[["date", keyword]].copy()
                df = df.rename(columns={keyword: "value"})

                output_file = output_folder / f"DatosGT_{country}_{keyword_clean}_bloque{bloque_i}_{today}.xlsx"
                df.to_excel(output_file, index=False)

                print(f"✅ Guardado: {output_file}")

                time.sleep(12)

            except Exception as e:
                print(f"❌ Error en {country} - {keyword} - bloque {bloque_i}: {e}")
                time.sleep(30)